[versions]
kotest = "5.9.1"
kotlin = "2.2.21"
okhttp = "4.12.0"
spotless = "6.25.0"

[libraries]
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
reckon = { id = "org.ajoberstar.reckon", version = "0.18.3" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
